* Installation

#+BEGIN_SRC sh
  git clone git@github.com:noahfrederick/dots.git ~/.dots
#+END_SRC

I symlink the various files via Puppet, but you could just as well
do it manually:

#+BEGIN_SRC sh
  ln -s ~/.dots/bashrc ~/.bashrc
  # etc.
#+END_SRC

* Software
** Vim

[[http://vim.org][Vim]] is a free, cross-platform text editor based on vi. It has been
around since the early '90s and is arguably the best editor currently
in existence. Although Vim is admittedly better suited for writing
code than prose (largely because of its poor handling of soft-wrapped
lines), I use it for pretty much everything.

** Emacs

[[http://www.gnu.org/software/emacs/][Emacs]] is a free, cross-platform text editor, mail client, news reader,
organizer, and more. It is the second-best text editor currently in
existence. It does not take the streamlined, minimalistic approach
that Vim does, but it can be made to emulate Vim. I use Emacs for the
excellent [[http://orgmode.org][Org mode]]. See my [[emacs.d/emacs.org][emacs.org]] file for more.

** Fish

My shell of choice is the [[http://fishshell.com][fish shell]].
More software ought to be developed with [[http://fishshell.com/docs/current/design.html][fish's design guidelines]] in
mind.

** Tmux

[[http://tmux.sourceforge.net][Tmux]] is a popular terminal multiplexer.
