Personal configuration files and miscellaneous scripts for the
platforms I work on (mostly OS X).

* Installation

#+BEGIN_SRC sh
  git clone git@github.com:noahfrederick/dots.git ~/.dots
#+END_SRC

I symlink the various files via Puppet, but you could just as well
do it manually:

#+BEGIN_SRC sh
  ln -s ~/.dots/bashrc ~/.bashrc
  # etc.
#+END_SRC

* Software
** Vim

[[http://vim.org][Vim]] is a free (liber) cross-platform text editor based on vi. It has
been around since the early '90s and is arguably the best editor
currently in existence. Although Vim is admittedly better suited for
writing code than prose (largely because of its poor handling of
soft-wrapped lines), I use it for pretty much everything.

On OS X, install Vim with Homebrew:

#+BEGIN_SRC sh
  brew install macvim --override-system-vim --with-lua --with-luajit
#+END_SRC

Ruby and Python support is compiled in by default as of this writing.

Plug-ins are managed with a CLI utility called [[vim/bin/README.md][spore]] in conjunction
with [[https://github.com/tpope/vim-pathogen][pathogen.vim]].

** Emacs

[[http://www.gnu.org/software/emacs/][Emacs]] is a free (liber) cross-platform text editor, mail client, news
reader, organizer, and more. It is the second-best text editor
currently in existence. It does not take the streamlined, minimalistic
approach that Vim does, but it can be made to emulate Vim. I use Emacs
for the excellent [[http://orgmode.org][Org mode]].

On OS X, install Emacs with Homebrew:

#+BEGIN_SRC sh
  brew install emacs --cocoa --srgb
#+END_SRC

For instructions on how to install packages etc., see my [[emacs.d/emacs.org][emacs.org]]
file.

** Fish

My shell of choice is the [[http://fishshell.com][fish shell]].
More software ought to be developed with [[http://fishshell.com/docs/current/design.html][fish's design guidelines]] in
mind.

#+BEGIN_SRC sh
  brew install fish
#+END_SRC

** Tmux

[[http://tmux.sourceforge.net][Tmux]] is a popular terminal multiplexer.

#+BEGIN_SRC sh
  brew install tmux
#+END_SRC

