" Set colors
colorscheme styx

" Hide toolbar and scrollbars by default
" (see :help 'guioptions')
set guioptions=gmt

set visualbell
set spell
set number

if has('gui_macvim')
  set guifont=Panic\ Sans:h13

  " Panic Sans needs a little vertical breathing room
  set linespace=2

  set fullscreen

  " Toggle window transparency - useful for referencing something behind Vim
  nnoremap <silent> <Leader>0 :let &transparency = (&transparency == "0" ? "30" : "0")<CR>
endif

" vim: fdm=marker:sw=2:sts=2:et
