" Set colors
colorscheme styx

" Set font
set guifont=Panic\ Sans:h13

" Panic Sans needs a little vertical breathing room
set linespace=2

" Hide toolbar and scrollbars by default
" (see :help 'guioptions')
set guioptions=gmt

set visualbell
set spell
set number

set fullscreen

" Toggle window transparency - useful for referencing something behind Vim
nnoremap <silent> <Leader>0 :let &transparency = (&transparency == "0" ? "30" : "0")<CR>

" vim: fdm=marker:sw=2:sts=2:et
