" Set colors
colorscheme styx

" Hide toolbar and scrollbars by default
" (see :help 'guioptions')
set guioptions=gmt

set visualbell
set spell

if has('gui_macvim')
  " Has the nice '<>', excellent legibility, easy to distinguish among
  " punctuation marks
  set guifont=Source\ Code\ Pro:h14
  set linespace=0

  " Has the nice '<>', dotted '0', good punctuation, good legibility overall,
  " but missing italics
  " set guifont=Fira\ Mono:h14
  " set linespace=0

  " Has the nice '<>', great italics, but slashed '0' and feels a little heavy
  " set guifont=Fantasque\ Sans\ Mono:h16
  " set linespace=3

  " Dashes are too short, underscores too thin
  " set guifont=DejaVu\ Sans\ Mono:h13
  " set linespace=2

  " Has slashed '0' instead of dot
  " set guifont=Menlo:h13
  " set linespace=2

  " Poor legibility of certain letters
  " set guifont=Ubuntu\ Mono:h15
  " set linespace=2

  " Non-ASCII characters show up too small
  " set guifont=Panic\ Sans:h13
  " set linespace=2

  " Toggle window transparency - useful for referencing something behind Vim
  nnoremap <silent> <Leader>0 :let &transparency = (&transparency == "0" ? "30" : "0")<CR>
endif

command! -nargs=0 -bar Present
      \ set nospell nonumber nolist cmdheight=1 scrolloff=0 |
      \ let &guifont = substitute(&guifont, '\d\+$', '34', '') |
      \ highlight StatusLine   guifg=#000000 guibg=#dddddd |
      \ highlight StatusLineNC guifg=#888888 guibg=#dddddd |
      \ highlight Wildmenu     guifg=#000000 guibg=#dddddd |
      \ highlight User1        guifg=#ff0055 guibg=#dddddd |
      \ highlight User2        guifg=#539dbd guibg=#dddddd |
      \ highlight User3        guifg=#b1d631 guibg=#dddddd |
      \ silent! GitGutterDisable

" vim: fdm=marker:sw=2:sts=2:et
